### ISSUE TITLE
Any way to reliably detect infiniband eth1?

### ISSUE THREAD

**Issue by abagshaw** [Azure/azhpc-images#29]
On RDMA enabled instances (both with SR-IOV and without) it appears that there is a nic that shows up as `eth1`. This is before installing any drivers (just off of the base `ubuntu18` image). Azure IMDS also shows this second nic in IMDS in the `interface` array, although there is no IP associated with it.

I'm not sure if this is an IPoIB nic, but regardless it is interfering with our interface naming because we also have a secondary NIC that is attached to the VM. On non-RDMA instances this secondary nic we attach will show up as `eth1`, but on RDMA enabled instances it gets bumped down to `eth2` because of this infiniband nic.

Is there any reliable way to create a generic udev rule/init.d script that will be baked into our image that can detect the rdma `eth1` so that we can rename it? We need this rule to work before the network is up so it can't rely on IMDS or the `SharedConfig.xml`.

**Comment by jithinjosepkl** [comment]
@abagshaw , you may want to use two different images here - one for IB-enabled SKUs and one for non-IB. I dont see any other option especially since you are checking this in the udev rules processing time. Also, checking the MAC range is not a bad idea tbh, the range is ~65K. It may take sometime to go over that limit in a single cluster.

I am closing this issue as this is not related to the images.
