### ISSUE TITLE
Can you add tags with the image version when published in the marketplace 

### ISSUE THREAD

**Issue by xpillons** [Azure/azhpc-images#40]
The image version number in the azure marketplace is different from your tagging, making impossible to knows what contains the images deployed. 
For example to which tag in this repo this version relates to 7.7.2020121000 ?

**Comment by anshuljainansja** [comment]
It is difficult to keep the version number in the Azure marketplace and the tags in this repository to be in sync.

The images on the Azure marketplace could be updated and published because of multiple reasons.

As a workaround what I have done is that I have added a file, /opt/azurehpc/azhpc-version, which will contain the corresponding tag from this repository.

This will be available in the future releases of CentOS 7.6, 7.7, 7.8, and 8.1 HPC images.

**Comment by xpillons** [comment]
If so then it would be interesting to add in that file the versions of the main components being installed in the image

**Comment by jithinjosepkl** [comment]
This is added in new images.
